import http from 'node:http';
import { readFile, stat } from 'node:fs/promises';
import { mkdirSync, existsSync } from 'node:fs';
import { DatabaseSync } from 'node:sqlite';
import { randomBytes, createHash, scryptSync, timingSafeEqual } from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root=path.dirname(fileURLToPath(import.meta.url)); mkdirSync(path.join(root,'data'),{recursive:true});
const db=new DatabaseSync(path.join(root,'data/pizza-house.db')); db.exec('PRAGMA foreign_keys = ON;');
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,phone TEXT NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN ('admin','customer')),status TEXT NOT NULL DEFAULT 'active',created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS admin_registration(id INTEGER PRIMARY KEY CHECK(id=1),code_hash TEXT NOT NULL,used INTEGER DEFAULT 0,used_at TEXT);
CREATE TABLE IF NOT EXISTS sessions(id INTEGER PRIMARY KEY,user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,token_hash TEXT UNIQUE NOT NULL,expires_at TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS categories(id INTEGER PRIMARY KEY,name TEXT UNIQUE NOT NULL,image TEXT,active INTEGER DEFAULT 1);
CREATE TABLE IF NOT EXISTS products(id INTEGER PRIMARY KEY,name TEXT NOT NULL,description TEXT NOT NULL,category_id INTEGER REFERENCES categories(id),image TEXT,price REAL NOT NULL CHECK(price>=0),old_price REAL,discount REAL DEFAULT 0,sizes TEXT DEFAULT '[]',addons TEXT DEFAULT '[]',available INTEGER DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS coupons(id INTEGER PRIMARY KEY,code TEXT UNIQUE NOT NULL,discount_type TEXT CHECK(discount_type IN ('percentage','fixed')) NOT NULL,discount_value REAL NOT NULL,minimum_order REAL DEFAULT 0,maximum_discount REAL,usage_limit INTEGER,used_count INTEGER DEFAULT 0,start_date TEXT,end_date TEXT,active INTEGER DEFAULT 1);
CREATE TABLE IF NOT EXISTS orders(id INTEGER PRIMARY KEY,order_number TEXT UNIQUE NOT NULL,user_id INTEGER NOT NULL REFERENCES users(id),subtotal REAL NOT NULL,discount REAL NOT NULL,delivery_fee REAL NOT NULL,total REAL NOT NULL,payment_method TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'Pending',address TEXT NOT NULL,notes TEXT,coupon_code TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS order_items(id INTEGER PRIMARY KEY,order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,product_id INTEGER,product_name_snapshot TEXT NOT NULL,price_snapshot REAL NOT NULL,quantity INTEGER NOT NULL CHECK(quantity>0),size TEXT,addons TEXT DEFAULT '[]');
CREATE TABLE IF NOT EXISTS restaurant_settings(id INTEGER PRIMARY KEY CHECK(id=1),restaurant_name TEXT NOT NULL DEFAULT 'Pizza House',logo TEXT,phone TEXT DEFAULT '+20 100 555 0188',email TEXT DEFAULT 'hello@pizzahouse.local',address TEXT DEFAULT 'Downtown, Cairo',delivery_fee REAL DEFAULT 25,minimum_order REAL DEFAULT 80,opening_hours TEXT DEFAULT 'Daily · 11:00 AM – 1:00 AM',hero_title TEXT DEFAULT 'Fresh Pizza. Big Flavor.',hero_description TEXT DEFAULT 'Hand-stretched dough, bold ingredients, and a table waiting for you.');
CREATE INDEX IF NOT EXISTS orders_user_idx ON orders(user_id,created_at); CREATE INDEX IF NOT EXISTS products_category_idx ON products(category_id,available);`);
if(!db.prepare('SELECT id FROM restaurant_settings WHERE id=1').get()) db.prepare('INSERT INTO restaurant_settings(id) VALUES(1)').run();
const cats=['Pizza','Burgers','Pasta','Appetizers','Chicken','Desserts','Drinks','Combos']; for(const name of cats) db.prepare('INSERT OR IGNORE INTO categories(name) VALUES(?)').run(name);
const seed=db.prepare('SELECT count(*) n FROM products').get().n; if(!seed){ const cid=db.prepare('SELECT id FROM categories WHERE name=?'); const add=db.prepare('INSERT INTO products(name,description,category_id,image,price,old_price,discount,sizes,addons) VALUES(?,?,?,?,?,?,?,?,?)'); [['Truffle Margherita','San Marzano tomato, fior di latte, basil & truffle oil','Pizza','https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=900&q=85',189,220,14,'["Medium","Large"]','["Extra mozzarella","Basil"]'],['Smoky Pepperoni','Crisp pepperoni, mozzarella, hot honey','Pizza','https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&w=900&q=85',205,null,0,'["Medium","Large"]','["Extra pepperoni","Jalapeños"]'],['House Smash Burger','Double beef, aged cheddar, house sauce','Burgers','https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=85',165,190,13,'[]','["Fries","Bacon"]'],['Creamy Alfredo','Fresh pasta, parmesan, roasted chicken','Pasta','https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=900&q=85',175,null,0,'[]','["Chicken","Mushrooms"]'],['Golden Wings','Six crunchy wings, spicy glaze','Chicken','https://images.unsplash.com/photo-1527477396000-e27163b481c2?auto=format&fit=crop&w=900&q=85',125,null,0,'[]','["Ranch dip"]'],['Tiramisu Cloud','Mascarpone, cocoa, espresso','Desserts','https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&w=900&q=85',85,null,0,'[]','[]']].forEach(x=>add.run(x[0],x[1],cid.get(x[2]).id,x[3],x[4],x[5],x[6],x[7],x[8])); }
function hash(v){const salt=randomBytes(16).toString('hex');return `${salt}:${scryptSync(v,salt,64).toString('hex')}`}; function valid(v,h){const [s,k]=h.split(':');const a=Buffer.from(k,'hex'),b=scryptSync(v,s,64);return a.length===b.length&&timingSafeEqual(a,b)}
function json(res,status,data,headers={}){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8',...headers});res.end(JSON.stringify(data))} function parseCookies(req){return Object.fromEntries((req.headers.cookie||'').split(';').filter(Boolean).map(x=>x.trim().split('=').map(decodeURIComponent)))}
async function body(req){let s='';for await(const x of req){s+=x;if(s.length>1e6)throw Error('Payload too large')}try{return s?JSON.parse(s):{}}catch{throw Error('Invalid JSON')}}
function user(req){const t=parseCookies(req).ph_session;if(!t)return null; return db.prepare('SELECT u.id,u.name,u.email,u.phone,u.role,u.status FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>datetime(\'now\')').get(createHash('sha256').update(t).digest('hex'))||null} function auth(req,res,admin=false){const u=user(req); if(!u||u.status!=='active'||(admin&&u.role!=='admin')){json(res,u?403:401,{error:u?'Forbidden':'Authentication required'});return null}return u}
function session(res,id){const t=randomBytes(32).toString('base64url');db.prepare('INSERT INTO sessions(user_id,token_hash,expires_at) VALUES(?,?,datetime(\'now\',\'+7 days\'))').run(id,createHash('sha256').update(t).digest('hex'));return `ph_session=${t}; HttpOnly; SameSite=Lax; Path=/; Max-Age=604800`}
function settings(){return db.prepare('SELECT * FROM restaurant_settings WHERE id=1').get()} function productRows(where='',args=[]){return db.prepare(`SELECT p.*,c.name category FROM products p JOIN categories c ON c.id=p.category_id ${where} ORDER BY p.created_at DESC`).all(...args).map(p=>({...p,sizes:JSON.parse(p.sizes),addons:JSON.parse(p.addons)}))}
function coupon(code,subtotal){const c=db.prepare('SELECT * FROM coupons WHERE upper(code)=upper(?)').get(code);if(!c||!c.active)throw Error('Invalid coupon code.'); if(c.start_date&&c.start_date>new Date().toISOString())throw Error('This coupon is not active yet.');if(c.end_date&&c.end_date<new Date().toISOString())throw Error('This coupon has expired.');if(c.usage_limit!==null&&c.used_count>=c.usage_limit)throw Error('This coupon has reached its usage limit.');if(subtotal<c.minimum_order)throw Error(`Minimum order is EGP ${c.minimum_order}.`);let d=c.discount_type==='percentage'?subtotal*c.discount_value/100:c.discount_value;if(c.maximum_discount!==null)d=Math.min(d,c.maximum_discount);return {c,discount:Math.min(d,subtotal)}}
const routes=async(req,res)=>{const url=new URL(req.url,'http://x'),p=url.pathname,m=req.method;try{
 if(p==='/api/settings'&&m==='GET')return json(res,200,settings()); if(p==='/api/categories'&&m==='GET')return json(res,200,db.prepare('SELECT * FROM categories WHERE active=1').all());
 if(p==='/api/products'&&m==='GET'){let q='WHERE p.available=1 AND c.active=1',a=[];if(url.searchParams.get('category')){q+=' AND c.name=?';a.push(url.searchParams.get('category'))}if(url.searchParams.get('q')){q+=' AND (p.name LIKE ? OR p.description LIKE ?)';a.push('%'+url.searchParams.get('q')+'%','%'+url.searchParams.get('q')+'%')}if(url.searchParams.get('offers')==='1')q+=' AND p.discount>0';return json(res,200,productRows(q,a))}
 if(p==='/api/auth/me'&&m==='GET')return json(res,200,{user:user(req)});
 if(p==='/api/auth/register'&&m==='POST'){const b=await body(req);if(!b.name||!/^\S+@\S+\.\S+$/.test(b.email)||!b.phone||!b.password||b.password.length<8)throw Error('Provide a name, valid email, phone, and password of at least 8 characters.');try{const r=db.prepare("INSERT INTO users(name,email,phone,password_hash,role) VALUES(?,?,?,?, 'customer')").run(b.name.trim(),b.email.toLowerCase(),b.phone.trim(),hash(b.password));return json(res,201,{user:{id:Number(r.lastInsertRowid),name:b.name,email:b.email,role:'customer'}},{'Set-Cookie':session(res,r.lastInsertRowid)})}catch{throw Error('Email already exists.') }}
 if(p==='/api/auth/login'&&m==='POST'){const b=await body(req),u=db.prepare('SELECT * FROM users WHERE email=?').get((b.email||'').toLowerCase());if(!u||!valid(b.password||'',u.password_hash))return json(res,401,{error:'Wrong email or password.'});if(u.status!=='active')return json(res,403,{error:'This account has been disabled.'});if(b.admin&&u.role!=='admin')return json(res,403,{error:'Use the customer login for this account.'});return json(res,200,{user:{id:u.id,name:u.name,email:u.email,role:u.role}},{'Set-Cookie':session(res,u.id)})}
 if(p==='/api/auth/logout'&&m==='POST'){const t=parseCookies(req).ph_session;if(t)db.prepare('DELETE FROM sessions WHERE token_hash=?').run(createHash('sha256').update(t).digest('hex'));return json(res,200,{ok:true},{'Set-Cookie':'ph_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0'})}
 if(p==='/api/admin/bootstrap/status'&&m==='GET')return json(res,200,{needed:!db.prepare("SELECT id FROM users WHERE role='admin'").get()});
 if(p==='/api/admin/bootstrap'&&m==='POST'){const b=await body(req);if(db.prepare("SELECT id FROM users WHERE role='admin'").get())return json(res,409,{error:'Admin registration code has already been used.'});const code=process.env.ADMIN_REGISTRATION_CODE;if(!code||!b.code||!timingSafeEqual(Buffer.from(code),Buffer.from(b.code)))return json(res,403,{error:'Invalid admin registration code.'});if(!b.name||!/^\S+@\S+\.\S+$/.test(b.email)||!b.password||b.password.length<8)throw Error('Enter valid admin details and a password of at least 8 characters.');const r=db.prepare("INSERT INTO users(name,email,phone,password_hash,role) VALUES(?,?,?,?, 'admin')").run(b.name,b.email.toLowerCase(),b.phone||'Admin',hash(b.password));db.prepare('INSERT OR REPLACE INTO admin_registration(id,code_hash,used,used_at) VALUES(1,?,?,CURRENT_TIMESTAMP)').run(hash(code),1);return json(res,201,{ok:true},{'Set-Cookie':session(res,r.lastInsertRowid)})}
 if(p==='/api/coupons/validate'&&m==='POST'){const b=await body(req);return json(res,200,coupon(b.code,Number(b.subtotal)||0));}
 if(p==='/api/orders'&&m==='POST'){const u=auth(req,res);if(!u)return;const b=await body(req);if(!Array.isArray(b.items)||!b.items.length)throw Error('Your cart is empty.');const ids=[...new Set(b.items.map(i=>Number(i.productId)))];const rows=db.prepare(`SELECT * FROM products WHERE id IN (${ids.map(()=>'?').join(',')}) AND available=1`).all(...ids);if(rows.length!==ids.length)throw Error('One or more selected products are unavailable.');let subtotal=0,items=[];for(const i of b.items){const pr=rows.find(x=>x.id===Number(i.productId)),qty=Math.floor(Number(i.quantity));if(!pr||qty<1||qty>20)throw Error('Invalid cart quantity.');const sizes=JSON.parse(pr.sizes),adds=JSON.parse(pr.addons);if(i.size&&!sizes.includes(i.size))throw Error('Invalid product size.');const ad=Array.isArray(i.addons)?i.addons:[];if(ad.some(x=>!adds.includes(x)))throw Error('Invalid product add-on.');subtotal+=pr.price*qty;items.push({pr,qty,size:i.size||null,addons:ad})}const s=settings();if(subtotal<s.minimum_order)throw Error(`Minimum order is EGP ${s.minimum_order}.`);let disc=0,c=null;if(b.coupon){const x=coupon(b.coupon,subtotal);disc=x.discount;c=x.c}const fee=s.delivery_fee,total=subtotal-disc+fee,addr=[b.fullName,b.phone,b.address,b.city,b.building].filter(Boolean).join(', ');if(!b.fullName||!b.phone||!b.address||!b.city)throw Error('Please complete your delivery details.');const no='PH-'+(10000+Math.floor(Math.random()*89999));db.exec('BEGIN');try{const r=db.prepare('INSERT INTO orders(order_number,user_id,subtotal,discount,delivery_fee,total,payment_method,address,notes,coupon_code) VALUES(?,?,?,?,?,?,?,?,?,?)').run(no,u.id,subtotal,disc,fee,total,'Cash on Delivery',addr,b.notes||'',c?.code||null);const oi=db.prepare('INSERT INTO order_items(order_id,product_id,product_name_snapshot,price_snapshot,quantity,size,addons) VALUES(?,?,?,?,?,?,?)');items.forEach(x=>oi.run(r.lastInsertRowid,x.pr.id,x.pr.name,x.pr.price,x.qty,x.size,JSON.stringify(x.addons)));if(c)db.prepare('UPDATE coupons SET used_count=used_count+1 WHERE id=?').run(c.id);db.exec('COMMIT');return json(res,201,{orderNumber:no,total})}catch(e){db.exec('ROLLBACK');throw e}}
 if(p==='/api/orders'&&m==='GET'){const u=auth(req,res);if(!u)return;const os=db.prepare('SELECT * FROM orders WHERE user_id=? ORDER BY created_at DESC').all(u.id);const it=db.prepare('SELECT * FROM order_items WHERE order_id=?');return json(res,200,os.map(o=>({...o,items:it.all(o.id).map(x=>({...x,addons:JSON.parse(x.addons)}))})))}
 if(p.startsWith('/api/admin')){const u=auth(req,res,true);if(!u)return;if(p==='/api/admin/dashboard'&&m==='GET'){const q=x=>db.prepare(x).get();return json(res,200,{sales:q("SELECT coalesce(sum(total),0) n FROM orders WHERE status='Delivered'").n,today:q("SELECT coalesce(sum(total),0) n FROM orders WHERE date(created_at)=date('now')").n,orders:q('SELECT count(*) n FROM orders').n,pending:q("SELECT count(*) n FROM orders WHERE status='Pending'").n,completed:q("SELECT count(*) n FROM orders WHERE status='Delivered'").n,cancelled:q("SELECT count(*) n FROM orders WHERE status='Cancelled'").n,customers:q("SELECT count(*) n FROM users WHERE role='customer'").n,products:q('SELECT count(*) n FROM products').n,popular:db.prepare('SELECT product_name_snapshot name,sum(quantity) quantity FROM order_items GROUP BY product_id ORDER BY quantity DESC LIMIT 5').all()})}
 if(p==='/api/admin/products'&&m==='GET')return json(res,200,productRows()); if(p==='/api/admin/products'&&m==='POST'){const b=await body(req);if(!b.name||!b.description||!Number.isFinite(+b.price)||+b.price<0||!b.categoryId)throw Error('Provide valid product details.');const r=db.prepare('INSERT INTO products(name,description,category_id,image,price,old_price,discount,sizes,addons,available) VALUES(?,?,?,?,?,?,?,?,?,?)').run(b.name,b.description,b.categoryId,b.image||'',+b.price,b.oldPrice?+b.oldPrice:null,b.discount?+b.discount:0,JSON.stringify(b.sizes||[]),JSON.stringify(b.addons||[]),b.available===false?0:1);return json(res,201,{id:r.lastInsertRowid})}
 const pm=p.match(/^\/api\/admin\/products\/(\d+)$/);if(pm&&m==='PUT'){const b=await body(req);db.prepare('UPDATE products SET name=?,description=?,category_id=?,image=?,price=?,old_price=?,discount=?,sizes=?,addons=?,available=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(b.name,b.description,b.categoryId,b.image||'',+b.price,b.oldPrice?+b.oldPrice:null,b.discount?+b.discount:0,JSON.stringify(b.sizes||[]),JSON.stringify(b.addons||[]),b.available===false?0:1,+pm[1]);return json(res,200,{ok:true})}if(pm&&m==='DELETE'){db.prepare('DELETE FROM products WHERE id=?').run(+pm[1]);return json(res,200,{ok:true})}
 if(p==='/api/admin/categories'&&m==='GET')return json(res,200,db.prepare('SELECT * FROM categories ORDER BY name').all());if(p==='/api/admin/categories'&&m==='POST'){const b=await body(req);if(!b.name)throw Error('Category name is required.');db.prepare('INSERT INTO categories(name,image,active) VALUES(?,?,?)').run(b.name,b.image||'',b.active===false?0:1);return json(res,201,{ok:true})}
 if(p==='/api/admin/coupons'&&m==='GET')return json(res,200,db.prepare('SELECT * FROM coupons ORDER BY id DESC').all());if(p==='/api/admin/coupons'&&m==='POST'){const b=await body(req);if(!b.code||!['percentage','fixed'].includes(b.discountType)||+b.discountValue<=0)throw Error('Coupon code and a valid discount are required.');db.prepare('INSERT INTO coupons(code,discount_type,discount_value,minimum_order,maximum_discount,usage_limit,start_date,end_date,active) VALUES(?,?,?,?,?,?,?,?,?)').run(b.code.toUpperCase(),b.discountType,+b.discountValue,+b.minimumOrder||0,b.maximumDiscount?+b.maximumDiscount:null,b.usageLimit?+b.usageLimit:null,b.startDate||null,b.endDate||null,b.active===false?0:1);return json(res,201,{ok:true})}
 if(p==='/api/admin/orders'&&m==='GET')return json(res,200,db.prepare('SELECT o.*,u.name customer,u.phone FROM orders o JOIN users u ON u.id=o.user_id ORDER BY o.created_at DESC').all());const om=p.match(/^\/api\/admin\/orders\/(\d+)\/status$/);if(om&&m==='PATCH'){const b=await body(req),ok=['Pending','Confirmed','Preparing','Out for Delivery','Delivered','Cancelled'];if(!ok.includes(b.status))throw Error('Invalid order status.');db.prepare('UPDATE orders SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(b.status,+om[1]);return json(res,200,{ok:true})}
 if(p==='/api/admin/customers'&&m==='GET')return json(res,200,db.prepare("SELECT u.id,u.name,u.email,u.phone,u.status,u.created_at,count(o.id) order_count,coalesce(sum(o.total),0) total_spent FROM users u LEFT JOIN orders o ON o.user_id=u.id WHERE u.role='customer' GROUP BY u.id ORDER BY u.created_at DESC").all());if(p==='/api/admin/settings'&&m==='PUT'){const b=await body(req),prev=settings();const fields=['restaurant_name','logo','phone','email','address','delivery_fee','minimum_order','opening_hours','hero_title','hero_description'];const vals=fields.map(k=>b[k]??prev[k]);db.prepare(`UPDATE restaurant_settings SET ${fields.map(k=>k+'=?').join(',')} WHERE id=1`).run(...vals);return json(res,200,{ok:true})}}
 return json(res,404,{error:'Not found'});
}catch(e){return json(res,400,{error:e.message||'Server error'})}};
const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.png':'image/png'};
http.createServer(async(req,res)=>{if(req.url.startsWith('/api/'))return routes(req,res);let f=path.join(root,'public',new URL(req.url,'http://x').pathname);if(f.endsWith('/'))f+= 'index.html';try{if(!existsSync(f)||(await stat(f)).isDirectory())f=path.join(root,'public','index.html');const ext=path.extname(f);res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream','Cache-Control':ext==='.html'?'no-cache':'public, max-age=3600'});res.end(await readFile(f))}catch{res.writeHead(404);res.end('Not found')}}).listen(process.env.PORT||3000,()=>console.log(`Pizza House running at http://localhost:${process.env.PORT||3000}`));
